language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
script:
- npm run eslint
- npm run jscs
- npm run test-cov
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: dev@adrianhaasler.com
  api_key:
    secure: MVAf1uFIdIsJqI3Rts4RWd4o5BuDtn0AQnFKaWEzHn5rm3ruCTCFi5p8tztJ+8XPMpl2Cf80VskccDOi8yzAIy6W74THDG269JlJsJi+YIR4DB0PW6DWuQOSAaVeJQdUsPtcNzQ6ferUi4sWzOdezkg7NTJMfwPez7S7SN1mCKOlp9mr9p20+jQCHqAObaI8SCdXoReLs5DwG9+Fyxgm/nttr/xT7w6CHzpTPb55wPf++6Czvnfrxmv+NGGjAIEM9DETOZ3ja7fN+ODYH/VVKJydYDib1F6vdpYjB04qZ+VLwkE6I4JFF3xzH4FXo1E2VeTVhBX8HsTxeqOLoP8j7SUudDtSWXqqEwfODNFbT1vxnGp0+l1+yGnq4BVk+zsxYBGJaLmrYFd/CjI9pvVgHw27nida1yr6UEOyAN/oRwBCWp+dvKNNal6TOFq3zdIoZ27XlcBjMHlBaK8XxN6puCxdGqzeWNT5CKKezwM3cqI6/1k6gikh9pcS4jwKDSE+rmE3CmEpupmecLEgnel7+hB64htLBiWHsH/Dhjv4XBIIpWa9yrzWJKEEguMe0AQBOk6Uq7+UL/pyJn//2b6ztnc2zlonEdAOo3rcM7JE3HlzlWKeR5klQhtooD7UYz5WqHibl6fXUUczT1lKFdM0Eaex2p2MhQ0+DD5OR5acF3M=
  on:
    tags: true
    repo: ahaasler/hexo-generator-multilingual-index
    node: '0.12'
